
# This file orchestrates the FastAPI application, Qdrant vector database for RAG development environment.
services:
  # --- 1. FastAPI Application Service (The API Layer) ---
  api:
    image: gowthambc/n26rag:v2.0
    container_name: n26-rag-backend
    # Expose FastAPI on the host machine's port 8000
    ports:
      - "8000:8000"
    working_dir: /usr/src/app # Set a new working directory for the project root
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # Essential environment variables for the FastAPI app to connect to other services
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY} 
      # Use the Docker service names for inter-container communication
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      # FIX: Ensure the application uses the Docker service name 'qdrant' instead of 'localhost'
      QDRANT_URL: http://qdrant:6333
    # Ensure Qdrant and Ollama are ready before starting the API
    depends_on:
      - qdrant
    # Use a restart policy suitable for development
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/data
    networks:
      - rag-network

  # --- 2. Qdrant Vector Database Service ---
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    # Expose the Qdrant API (6333) and the web UI (6333)
    ports:
      - "6333:6333"
    # Persist the vector data on a named volume
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

# --- Docker Volumes for Persistent Storage ---
volumes:
  qdrant_data: # Retained for Qdrant storage

# --- Docker Network (Ensures all services can communicate by name) ---
networks:
  rag-network:
    driver: bridge
